# Generated by Django 5.2.12 on 2026-03-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="courses/"),
        ),
    ]
