# Generated by Django 5.2.12 on 2026-03-23 20:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_comment_shared_with_friend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="shared_with",
        ),
        migrations.AddField(
            model_name="expense",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_expenses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
